# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jérémy Roche
titleimg: https://avatars0.githubusercontent.com/u/10939826?s=460&v=4
subtitle: Fullstack Engineer @Situ8ed
email: jeremyroche5@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  📍 Grenoble - France
baseurl: "" # the subpath of your site, e.g. /blog
url: "Jeremy38100.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# logo
logo-gerrit: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Gerrit_icon.svg/1200px-Gerrit_icon.svg.png
logo-java: http://tecnologiaenvivo.com/wp-content/uploads/2015/04/JAVA-ICON.png
logo-cpp: https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1200px-ISO_C%2B%2B_Logo.svg.png
logo-grafana: https://logodix.com/logo/1736776.png
logo-python: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1024px-Python-logo-notext.svg.png
logo-js: https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/1200px-Unofficial_JavaScript_logo_2.svg.png
logo-d3: https://raw.githubusercontent.com/d3/d3-logo/master/d3.png
logo-angular: https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/1200px-Angular_full_color_logo.svg.png
logo-ionic: https://miro.medium.com/max/512/1*eWai1Gz7mh2UOddtau5MGg.png
logo-appengine: https://miro.medium.com/max/498/1*VHYGqjhONSJ20pRlIUbg7w.png
logo-jenkins: https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Jenkins_logo.svg/226px-Jenkins_logo.svg.png

logo-uga: https://www.univ-grenoble-alpes.fr/medias/photo/logo-uga_1536325456233-png?ID_FICHE=177412

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
